### PR TITLE
creating system ob from a prediction was added

### PR DESCRIPTION
**Pull request by Katy-katy**

### CODE REVIEW

**Comment by lensonp** [comment]
@Katy-katy - I encountered this build error in my branch as well- must have been a matplotlib update. I fixed it in #132.

**Comment by Katy-katy** [comment]
@lensonp Great! I will fix it in the same way (to make this pull-request to
pass the tests)

**Comment by Katy-katy** [comment]
@lensonp  now I am going to work on scaling of output, but I will create a new branch for it

**Comment by lensonp** [comment]
@Katy-katy - I think we should build out the "noise" models and add them to predict(), and to system_from_prediction(), before merging this one. Do you want to do that?

**Comment by Katy-katy** [comment]
@lensonp Yes, I've just started working on it

**Comment by lensonp** [comment]
@Katy-katy - Good question. I think the noise_classifier should go in the same place as the system_classifier. Then, I think there should be a directory (regressors/noise), with subdirectories for each noise_model (for now, just regressors/noise/flat). All of the parameters (for now just I0) should have regression models in there. 

So, for now, we only add:
- classifiers/noise_classifier.yml
- regressors/noise/flat/I0_fraction.yml

Does that seem reasonable?

**Comment by Katy-katy** [comment]
@lensonp  it is not ready yet - I need to integrate the noise model in prediction / creating of Sys object

**Comment by lensonp** [comment]
@Katy-katy - We should resolve this I_factor issue before merging. Most other things look good.

If you can resolve it, go ahead; this would be a good use case for pdb. If not, can you send me the script (+data) that you are using to test it? I can figure it out tomorrow.

I notice a comment (models.__init__, line 325):
#TODO test the next line!
... did you take care of this? If so, would be good to remove this comment.

**Comment by lensonp** [comment]
@Katy-katy Taking another look at models.__init__ line 325: this certainly needs attention. There is an undefined reference "pop_id".

**Comment by Katy-katy** [comment]
@lensonp I think, I fixed both problems. Now we are using "old" parameters for regression models and I_factor also is fixed. 
screen shot 2018-11-26 at 6 03 07 pm

**Comment by Katy-katy** [comment]
@lensonp wait, please. I think, there is a bug in the I0_fraction of the noise models. I am trying to fix it.

**Comment by Katy-katy** [comment]
@lensonp I am done - you can merge it. There is no bug. The problem: all coefs for noise I0_fraction model are 0.0. I thought it is a bug, but it is not. We have about 90% of zeros or values very close to zero for I0_fraction for noise in R1. The other values are 1.0. From our features, sklearn cannot create a good model to predict this value and just predict always 0.0. Since we are using regularization, sklearn also want to minimize the coefs. Thus, having all 0.0 is reasonable in this situation.

**Comment by lensonp** [comment]
@Katy-katy - this looks good. As I am reviewing models.__init__, I am now thinking maybe we should have a noise_classifier for each system_class, basically to handle the "noise" parameters at the same level as "population" parameters. I may implement this and ask you to review/test it before we merge... looking in to it now.

**Pull request merged**
