### PR TITLE
Database psql

### PR DESCRIPTION
**Pull request by Katy-katy**
@lensonp I am not sure how we should test it. I could write the tests, but in this case we need to put the user name / password of a test account. But this "test account" must be able to modify the tables. Should we create "test" tables and create a test account that can modify these test tables?

### CODE REVIEW

**Comment by lensonp** [comment]
@Katy-katy - I think we should test this part locally, similar to the way we used to run the tests against Citrination... if the api key is present, use it and run the test, else, skip the test.

**Comment by Katy-katy** [comment]
@lensonp O - yes, I forgot about this option. OK - I will create the tests and then let you know that it is ready

**Comment by Katy-katy** [comment]
@lensonp I think, now it is ready. you can test it using a file I sent to you by e-mail.

**Comment by lensonp** [comment]
@Katy-katy - After we merge #172, I think it would be a good idea to include some documentation about how the database was established. I just added a file to the doc directory for this purpose. While the DB installation process is still fresh in your memory, please take notes in doc/db_installation.rst.

**Comment by Katy-katy** [comment]
@lensonp now the docs are ready

**Pull request merged**
