### PR TITLE
new models for classification were added

### PR DESCRIPTION
**Pull request by Katy-katy**

### CODE REVIEW

**Comment by Katy-katy** [comment]
@lensonp  there is the summary of the results (I created this table for the group meeting):

Screen Shot 2019-04-02 at 4 58 01 PM

**Comment by lensonp** [comment]
Never mind my question- it looks like there are a few solutions for this, but globals are fine.

I learned some things by reading this:
https://stackoverflow.com/questions/1977362/how-to-create-module-wide-variables-in-python

**Comment by Katy-katy** [comment]
@lensonp yea... I read another post and it recommended use "global" (I did not save the link, it was also from stackoverflow)

**Comment by lensonp** [comment]
@Katy-katy - Finished review. PR coming up to suggest changes.

**Comment by lensonp** [comment]
@Katy-katy - Ok, this is good to go.

**Pull request merged**
