### PR TITLE
Visualization

### PR DESCRIPTION
**Pull request by Katy-katy**
Now we can run: 
visualize(save_results=True)

I will create two plots (by system_classes and by experiments) using all datasets  from source_dataset_ids.yml. It is also possible to provide a list of dataset ids to use for visualization.

### CODE REVIEW

**Comment by lensonp** [comment]
@Katy-katy
 
Also, it would be nice to only download one time during testing... I was thinking maybe the main system_classifier dataset would be a good one since it is the most diverse... and then pass that dataframe around to the different data-oriented test modules.

**Comment by Katy-katy** [comment]
@lensonp what do you mean "it would be nice to select which PCs to use in the plot"? Right now we reduce all features to two PCs. Then we use both of them (for x and y coordinates)

**Comment by Katy-katy** [comment]
I think, it is a good idea about downloading only once. In this case instead of downsample_and_train(
            [22,23,29,30],
            cl,
            save_samples=False,
            save_models=False,
            train_hyperparameters=False,
            test=True)

we should have something like:
data = downsample_Citrination_datasets(citrination_client, [22,23,29,30],
                                           save_samples=save_samples, test=test)
sys_cls = train_system_classifier(data, hyper_parameters_search=train_hyperparameters)
reg_models = train_regression_models(data, hyper_parameters_search=train_hyperparameters)

**Comment by lensonp** [comment]
@Katy-katy 

Plotting against different PCs: It is often informative to visualize prinicipal components other than PC0 and PC1. I might want to see how my data project onto PC1 vs. PC2, or PC3 vs. PC12.

Downloading dataset once and using it for all tests: you should only need to change the tests modules to accomplish this. I'll do it and submit a PR.

**Comment by Katy-katy** [comment]
@lensonp  Now we can select which PCs to use in the plot and which features to use for PCA. I think, if also could be useful to have possibility to visualize by features, without PCA. How do you think?

**Comment by lensonp** [comment]
@Katy-katy I just squashed the entire branch into 4 commits. I will merge it if it passes tests. If you want to review anything before that happens, let me know.

**Pull request merged**
