### PR TITLE
Feature elimination

### PR DESCRIPTION
**Pull request by Katy-katy**
@lensonp I think, it is ready. I updated only 5 files and I have all models in "untacked" files on my machine. But the summary shows that I deleted all models.

### CODE REVIEW

**Comment by Katy-katy** [comment]
@lensonp let me fix it

**Comment by lensonp** [comment]
@Katy-katy - I'm now rebasing this branch on dev, and then I will review it. If you are still working in this branch, please fetch and reset to the rebased version.

**Comment by Katy-katy** [comment]
@lensonp  Thank you for letting me know! I do not working on it right now ( I am working on db test fixing)

**Comment by Katy-katy** [comment]
@lensonp I merged your pull request. Now you can review it again.

**Pull request merged**
