### PR TITLE
Accuracy / error reports added

### PR DESCRIPTION
**Pull request by Katy-katy**

### CODE REVIEW

**Comment by lensonp** [comment]
I'm currently reviewing this, and will submit a PR for some minor fixes.

I am getting an error in the tests- did you run them on your local machine? xrsdkit.models.classifier has an undefined reference to model_selection.

**Comment by Katy-katy** [comment]
@lensonp  we have two warning. One of them about dividing by zero: sometimes when we run cross validation for regression models, we have only one sample in testing set. Thus, it has standard deviation zero. The second is about F1: sometimes we do not have "True" labels for a class (when we have all samples of this class in one experiment) - in this case we have F1 = 0 for this label.

**Comment by lensonp** [comment]
@Katy-katy - I just rebased this branch on dev (no conflicts) and force-pushed. If you continue working on it, please reset your local branch to the origin version. I am reviewing this for merge right now.

**Comment by Katy-katy** [comment]
@lensonp  OK - thank you for this note!

**Comment by lensonp** [comment]
@Katy-katy - These new training reports are awesome. I think we can make them a little better, but we should revisit that later, when we have more data for training. I'll approve a merge after some small changes.

**Pull request merged**
