### PR TITLE
yml summary was added; a bug in train_regression_models() and _classi…

### PR DESCRIPTION
**Pull request by Katy-katy**
…fication_models()was fixed

### CODE REVIEW

**Comment by lensonp** [comment]
@Katy-katy - This is a good start. I think it would be better to continue developing this to resolve issue #190. Do you want to do it, or should I?

**Comment by Katy-katy** [comment]
I think, I can do it. I have some questions and I put them in comment for issue #190

**Comment by Katy-katy** [comment]
@lensonp  it is not ready yet. Saving of the models in provided dir work, but I need add load_models() function.

**Comment by Katy-katy** [comment]
@lensonp I think, now it is ready.

**Comment by lensonp** [comment]
@Katy-katy - There are merge conflicts. Do you want to fix them, or should I?

**Comment by Katy-katy** [comment]
@lensonp Please, do it!

**Comment by lensonp** [comment]
@Katy-katy - OK, done. I see a couple things that could be better... will review in a minute.

**Comment by Katy-katy** [comment]
@lensonp I merged your pull-request here. So, now, I think it is ready.

**Pull request merged**
