### PR TITLE
Rfcv

### PR DESCRIPTION
**Pull request by Katy-katy**
@lensonp you can take a look on it. now we have hyperparameter search and then feature illumination. Now I am going to move hyperparam search into feature illumination as we discussed.

### CODE REVIEW

**Comment by Katy-katy** [comment]
@lensonp test failed for Python 2.7. I think, you mentioned before that we have a problem with Python 2.7 and it is OK for now, but I am not sure

**Comment by lensonp** [comment]
@Katy-katy - I will start reviewing this now. 

I just finished the new group assignment algorithm- PR coming up for that.

**Comment by lensonp** [comment]
@Katy-katy - the first thing I'd like to do here is remove the models from the PR. We will have to do a big re-training after we merge this and #174. We should push new model sets as infrequently as possible, since they seriously inflate the size of the repository.

**Comment by lensonp** [comment]
@Katy-katy - Ignore my earlier comment about removing the models- it looks like you actually deleted them, which is totally fine.

However, I'm not so sure that it's a good idea to include the "new_classifier" feature in this PR. Feature selection should be independent of the classifier structure, and I think these two independent features should be developed separately. I'm going to take a closer look and get back to you.

**Comment by Katy-katy** [comment]
@lensonp it is easy to fix. I can remove the last two commits and this branch will be about "new_classifier." I can create a different branch with "feature illumination"

**Comment by lensonp** [comment]
@Katy-katy - check out the "feature_elimination" branch, I just attempted to do that myself.

**Pull request closed without merging**
