### PR TITLE
Unified features

### PR DESCRIPTION
**Pull request by lensonp**
I will have to rebuild all PIF records with the new feature set before this gets merged. I'll do that today.

It would be nice to merge this before we finish #103.... but I have not yet checked whether the additional features will throw off the Citrination models.

### CODE REVIEW

**Comment by lensonp** [comment]
Yes- please read my comment above. I just started working on it.

**Comment by Katy-katy** [comment]
Sorry - I was focused on the changed you did in the files and did not see your first comment. Yes, I think we definitely need to finis this one first, and then move back to #103

**Comment by lensonp** [comment]
@Katy-katy 

The unified features should now be complete, but I have had some trouble updating the datasets. I think it is a problem on Citrination- I contacted them already. We will have to wait for the uploads to work before we merge this.

I will post another comment after the data upload. After that, we should test model training with the new features included, fix any bugs we find, and merge this.

**Comment by Katy-katy** [comment]
OK

**Comment by Katy-katy** [comment]
@lensonp 
I got a strange error in the tests for Python 3.5 only: No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself. I think, it should be not related with some small changes I did (the code works well on my machine). Should we increase the time for tests?

**Comment by lensonp** [comment]
Don't worry about the 3.5 build error. For the purposes of merging this PR, we don't need all builds to pass. We'll address bugs like this on the next release PR.

**Pull request merged**
