### PR TITLE
configuration file works

### PR DESCRIPTION
**Pull request by Katy-katy**
Initially, when classifiers and regressors directory is empty, we need run:

'''
   train_models_from_local_dataset(data_dir, output_dir) # no conf file - default values will be used
   update_models(output_dir) # to move models in xrsdkit
   make_conf_file(conf_file) # the file with default values for all models with be created
'''

Then you can update manually conf file and train again:

'''
train_models_from_local_dataset(data_dir, output_dir, conf_file) # setting from conf file will be used
update_models(output_dir) # to move models in xrsdkit
'''

To get the best for now models you need to change in conf file:

'''
- - - main_classifiers
          - crystalline_binary: {metric: precision, type: logistic_regressor}
            diffuse: {metric: accuracy, type: knn}
            diffuse__disordered: {metric: accuracy, type: linear_svm}
            diffuse_binary: {metric: precision, type: knn}
            disordered_binary: {metric: precision, type: knn}
        - - diffuse
          - noise_model: {metric: accuracy, type: logistic_regressor}
            pop0:
              form: {metric: accuracy, type: linear_svm_hinge}
'''

### CODE REVIEW

**Comment by Katy-katy** [comment]
@lensonp It looks like we cannot load from pickle sklearn models in python2 if they were created and saved in python3. I saved the models using protocol=2, but it still does not work. I found that some people posted the same question, but no answer :(

**Comment by lensonp** [comment]
@Katy-katy - Ok, I can think of three options here.

1) Take your previous comment about py2 vs. py3 and put it up as an "issue", deal with it later or let somebody else worry about it.
2) Start doing separate releases for py2 and py3.
3) Stop trying to release models along with the software. Instead, release the software and the datasets separately, make it easier to train the models on the user's platform, and start releasing and version-controlling the datasets. 

I think I like option 3, but I'm open to ideas.

In any case, I think this PR can be closed, since we already merged #201. I will be making a repository for xrsdkit with the flow reactor data. I would like to use this exact model configuration for it. Do you still have the config file that you used for this?

**Comment by Katy-katy** [comment]
@lensonp I also like option 3. May be we also should add sets of trained models for the dataset to the same repo. We can put a comment that this dataset works for Python3 only. The point for having a set of models somewhere is that if a user  does not want to spend time on model training he can try  to use xrsdkit with provided models. I agree that these models should not be a part of xrsdkit package  - they should live on a their own repo or on repo with datasets.

**Comment by Katy-katy** [comment]
I closed it.

**Pull request closed without merging**
