### PR TITLE
Flattening

### PR DESCRIPTION
**Pull request by lensonp**
This is finally done!

- Removes about 1000 lines and a lot of painful logic
- Removes a layer of modeling: no more species
- Many changes for handling our next datasets: polyatomic crystals, fractional occupancies, and size distributions of Guinier-Porod scatterers, for example
- Finished lattice and space group handling
- Parameters and settings that depend on other settings are now handled much cleaner

There are some updated .yml files on the ssrl_dev AFS (see the "new_dataset" directory). I will finish migrating the rest of the data tomorrow.

A comprehensive review would not be practical here, since most of the package is rewritten, but look over it for basic understanding, run your tests and add them to the test suite. I am opening the PR for us to discuss any further changes that need to be made before the merge.

After this is merged, I have some possibilities in mind for the next feature branches:
- Break top-level system classifier into parts (I have some ideas for this)
- Comprehensive test suite (push for full code coverage)

### CODE REVIEW

**Comment by lensonp** [comment]
@Katy-katy - I'm now working on rebuilding the test dataset, and then testing the model training process. I already found a few bugs... will push fixes soon.

**Comment by Katy-katy** [comment]
yes... there are some bugs - I also was fixing them but is it nor ready. Ok - push it when it will be ready and  I will review it again.

**Comment by Katy-katy** [comment]
@lensonp  one of the bugs I found was that we are trying to train the models for "unidentified" populations.

**Comment by Katy-katy** [comment]
@lensonp  some more small bugs:
1. modelable_form_settings vs modelable_form_factor_settings; 
2. add some import to train.py:
from . import regression_models_dir,classification_models_dir
from .regressor import Regressor
from .classifier import Classifier

3. train.py / downsample_by_group()
change sys_cls_lbl to sys_cls

4. train.py/train_classification_models():
-            for pnm in xrsdefs.noise_params[modnm]+['I0_fraction']:
+            for pnm in list(xrsdefs.noise_params[modnm].keys())+['I0_fraction']:

5.train_regression_models():
-                        for pnm in xrsdefs.additional_form_factor_params(form,{stg_nm:stg_label}):
+                        for pnm in xrsdefs.additional_form_factor_params(form_id,{stg_nm:stg_label}):

6. yml_tools.py
-    all_sys = read_xrsd_system_data(path_to_dir)
+    all_sys = read_all_experiments(path_to_dir)

**Comment by lensonp** [comment]
@Katy-katy - Ok, this should now be fixed. Let me know what you find!

**Pull request merged**
