### PR TITLE
test path was added

### PR DESCRIPTION
**Pull request by Katy-katy**
The main changes:
1. Now in the testing time we are using data from xrsdkit_testing_dataset. You need to update you r.xrsdkit_storage_host file:

    `
    example:

    192.99.99.998

    /path/to/training/dataset

    /path/to/test/dataset

    storage_user

    /home/.ssh/id_rsa
    `

2. Now the program is not crashing if there are the samples with the same ids. The first sample will be added, the next samples with the same id will be skipped and a message will be printed.

### CODE REVIEW

**Comment by lensonp** [comment]
@Katy-katy - Ok, here is what I am getting.

The test fails 4 times. The 4 error messages are:

db/__init__.py:225: 
exp_from_table = db.query('SELECT DISTINCT experiment_id FROM files').getresult()
pg.ProgrammingError: ERROR:  permission denied for relation files (x2)

db/__init__.py:307:
new_experiments = db.query("SELECT DISTINCT experiment_id " ...
pg.ProgrammingError: ERROR:  permission denied for relation files

db/__init__.py:356:
all_cl_labels = set([r[0] for r in db.query(q).getresult()])
pg.ProgrammingError: ERROR:  permission denied for relation samples

db/__init__.py:423:
data = db.query('SELECT * FROM training').dictresult()
pg.ProgrammingError: ERROR:  permission denied for relation training

**Comment by lensonp** [comment]
@Katy-katy - I just tried again using your credential from my machine- it works fine.

So, I suppose this must be a db user configuration issue.

I don't think we need to resolve it now.  Some day, if a co-developer wants DB access, you may have to solve it.

**Comment by Katy-katy** [comment]
@lensonp yea... it may be. I've just try to connect with db using your credential and terminal and it works: 
Screen Shot 2019-04-30 at 3 40 47 PM

**Comment by lensonp** [comment]
@Katy-katy - What if you use my credential and try to run the pytest? Does it work on your machine?

**Comment by Katy-katy** [comment]
@lensonp No, with your credential I got the same error message as you. But it is interesting, I can connect with db using your credential using the terminal

**Comment by lensonp** [comment]
@Katy-katy - Yes, the connection seems to be okay. I think there is something wrong with the user permissions at the "table" level. Maybe you have special permissions because you created those tables.

Anyway, let's go ahead and merge this for now. You can revisit this on the DB side if you want, and for now, you will be the only user that can use the DB. Like you suggested earlier, it would be a good idea to meet with IT about this- they can probably educate us about how to set up DB authentication properly.

**Pull request merged**
