### PR TITLE
Train predict xval fixes

### PR DESCRIPTION
**Pull request by lensonp**
This needs to be reviewed carefully. I expect that we will need to make more changes. I did only the minimum, just enough to pass tests. I did NOT review the training metrics to make sure they make sense.

It would be a good idea to review all training and prediction methods to look for bugs before approving this PR. Consider proper use of data structures, indexing, scaling, etc.

### CODE REVIEW

**Comment by Katy-katy** [comment]
@lensonp so, I merged your pull request here and now I will review both pull requests as one.

**Comment by Katy-katy** [comment]
@lensonp I found a problem and we need to think about possible solutions. Problem: self.scaler is fitted using all 21 features: xrsd_kit_model.py lines 172-173:

    self.scaler = preprocessing.StandardScaler()
    self.scaler.fit(data[profiler.profile_keys])

We do it in this way since we first standardize the data and THEN do feature selection. So, when we want to use the scaler, we need to path data[profiler.profile_keys] into it, not data[self.features]. 

The tests works, since we do not do feature selection in testing time. 

I think, one of possible solutions is to update the self.scaler after feature selection:

   self.scaler = preprocessing.StandardScaler()
   self.scaler.fit(data[self.features])

**Comment by lensonp** [comment]
@Katy-katy - like this?

**Comment by Katy-katy** [comment]
@lensonp  No, I mean in the train function:

    if select_features:
                model_feats = self._cross_validation_rfe(valid_data,model_feats)
                #update the scaler using only selected features
                self.scaler = preprocessing.StandardScaler()
                self.scaler.fit(model_data[model_feats])

I've just implemented it, but did not push yet

**Comment by lensonp** [comment]
@Katy-katy - This __is__ in the train() function.

**Pull request merged**
