### PR TITLE
Lattices

### PR DESCRIPTION
**Pull request by lensonp**
This is a proposed framework for computing crystal symmetries. It should allow us to extend xrsdkit to compute diffraction for various lattice systems as they show up in the training set, without having to do any more major rebuilds.

It would be unfair to ask for a detailed code review on the space group and symmetry definitions-- lots of materials science in there. Still, give it a quick look for nonsense code, and ask me questions if you want.

### CODE REVIEW

**Comment by lensonp** [comment]
It makes sense that this is failing. I added a property to the system structure, but the records in the database don't have this property yet.

There are a couple more changes to make for the properties- I will get those in this PR, upload a test dataset, and try again... on Monday.

**Comment by lensonp** [comment]
@Katy-katy - I think this is ready now. I pushed new records only to dataset 21. Can you test this (including training models) against dataset 21, and see if you find any mistakes? I will also test it, but not until tomorrow.

**Comment by Katy-katy** [comment]
@lensonp OK - I will do it tomorrow morning (from 9 to 10)

**Comment by Katy-katy** [comment]
@lensonp Did you change "unidentified" to "None" in the dataset 21? If you think that "None" is better we also should update the code where we are using "unidentified."  Right now, list(data['system_classification'].unique()) gives  [None, 'pop0_diffuse', 'pop0_diffuse__pop1_crystalline', 'pop0_diffuse__pop1_diffuse']  and trainable_regression_models(data) crashes since it cannot split None

**Comment by lensonp** [comment]
@Katy-katy - I think this is now ready for your review. If you approve and merge, I can resolve the conflicts for #135.

**Pull request merged**
