### PR TITLE
Gui

### PR DESCRIPTION
**Pull request by lensonp**
Changes:
- Improved the dat and yml file IO popup. The user selects a directory of .dat files OR a directory of .yml files, OR (if the .dat and .yml are in separate directories), they can select both. The .yml files are then matched to the correct .dat files programmatically. If a .yml file is not found, an empty one is created, but it is not saved to the filesystem until the user clicks the "save" button.
- The GUI now includes a pop-up for training and loading machine learning models.
- In order to show the user the results of loading datasets and training models, some of the functions that typically print() to the terminal now have an abstract message_callback(). When these functions are used from the GUI, the message_callback() prints to a Listbox widget in order to display the training results.

I think there may still be some bugs here. Please review (no rush), but don't merge until I get one more chance to look it over.

### CODE REVIEW

**Comment by lensonp** [comment]
@Katy-katy 

1) I don't know how to fix the Mac view issue, and I do not have a Mac that I can test it on. Last time I (almost) fixed this, I did it by assigning column weights (see lines 175-176), but it wasn't perfect. I guess we should just make the window wider. I just pushed an attempted fix. Does it work? If it does not work, can you look at the lines I just changed (149,175,176), and tune it to something that works for your machine?

2) Yes, this is unclear. There are two things that will fix this, but not in this PR. One, write good documentation. Two, add mouse-over pop-up "help" windows in the GUI, so when the user doesn't understand, they hover the mouse over a "?" icon and a pop-up explains what to do. I don't think either of these fixes is appropriate for the current PR- I want to do these in separate features, later.

As for your usage, after you click Finish/Load, you should then see the files available in the main GUI. Maybe I should make the "browser" window close automatically when the user pushes Finish/Load. I just did this and pushed it- what do you think?

**Comment by Katy-katy** [comment]
@lensonp 
1. it is little bit better - I will try to improve it tomorrow.
2. Yes, I think we should make the "browser" window close automatically

**Comment by Katy-katy** [comment]
@lensonp I did the pull request for (1).

2. It looks like we have a problem with matching files.
In "scattering data directory" I choose (I got it form our data repo): /Users/kate/Desktop/SLAC/xrsdkit_modeling/flowreactor_pd_nanoparticles/dataset/R0_201811


 After pressing "Finish/Load files" I see in the terminal:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/anaconda3/envs/slac_env/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Users/kate/Desktop/SLAC/xrsdkit/xrsdkit/visualization/gui.py", line 571, in _get_data_files_from_browser
    df_map = self._match_data_to_yml(df_list,sf_list)
  File "/Users/kate/Desktop/SLAC/xrsdkit/xrsdkit/visualization/gui.py", line 591, in _match_data_to_yml
    sys = load_sys_from_yaml(ymlf)
  File "/Users/kate/Desktop/SLAC/xrsdkit/xrsdkit/tools/ymltools.py", line 24, in load_sys_from_yaml
    with open(file_path, 'r') as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kate/Desktop/SLAC/xrsdkit_modeling/flowreactor_pd_nanoparticles/dataset/R0_201811/gridsearch19_dz_bgsub.yml'

The program tries to find corresponding yml file for each dat file. But in our data repo for 
yml: gridsearch19_dz_bgsub.yml, the corresponding file is gridsearch19_xrsd_system.dat, not
gridsearch19_dz_bgsub.dat'. 

It looks like we need to change _match_data_to_yml(self,data_files,yml_files): function (line 584) or change the names of yml files in our data repo.

**Comment by lensonp** [comment]
@Katy-katy - This is not actually a problem, but again, we need better documentation. If you __search__ for the .dat files, it will attempt to match them with .yml files of the same name, because the .dat files contain no information about the corresponding .yml file names. However, if you __search__ for .yml files, it will open them, discover the .dat file names, and match them correctly. This is documented in the source code, but again, we need to make it easier for a user to find this documentation.

**Comment by lensonp** [comment]
@Katy-katy - If you search for the .yml files instead of the .dat files, in the same case that you mentioned above, do you see it working correctly?

**Comment by Katy-katy** [comment]
@lensonp I choose "Approved" by mistake - I wanted to put the comment. If I search for .yml files instead of the .dat files it also does not work: 
Screen Shot 2019-05-17 at 2 31 18 PM





after pressing "Finish" in the terminal:
Exception in Tkinter callback
Traceback (most recent call last):
  File "/anaconda3/envs/slac_env/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Users/kate/Desktop/SLAC/xrsdkit/xrsdkit/visualization/gui.py", line 572, in _get_data_files_from_browser
    self._set_data_files(df_map)
  File "/Users/kate/Desktop/SLAC/xrsdkit/xrsdkit/visualization/gui.py", line 636, in _set_data_files
    self._next_data_file()
  File "/Users/kate/Desktop/SLAC/xrsdkit/xrsdkit/visualization/gui.py", line 643, in _next_data_file
    current_file_idx = file_list.index(current_file)
ValueError: 'flow_reactor_modeling_dataset/RxnA_201902/' is not in list

**Comment by Katy-katy** [comment]
@lensonp it looks like I cannot remove my "approving"

**Comment by lensonp** [comment]
@Katy-katy - I just ran this exact same test and it works for me. It looks you probably need to pull the latest version of the xrsdkit_modeling repository.

**Comment by lensonp** [comment]
I say that because:
1) There should only be about 10 samples in RxnA_201902.
2) The dataset directory for the flow reactor was renamed to "flowreactor_pd_nanoparticles".

**Comment by Katy-katy** [comment]
I have the same with the latest version.
My directory: /Users/kate/Desktop/SLAC/xrsdkit_modeling/flowreactor_pd_nanoparticles/dataset

I choose RxnA_201902:
Screen Shot 2019-05-18 at 1 13 28 PM

Traceback (most recent call last):
  File "/anaconda3/envs/slac_env/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Users/kate/Desktop/SLAC/xrsdkit/xrsdkit/visualization/gui.py", line 572, in _get_data_files_from_browser
    self._set_data_files(df_map)
  File "/Users/kate/Desktop/SLAC/xrsdkit/xrsdkit/visualization/gui.py", line 636, in _set_data_files
    self._next_data_file()
  File "/Users/kate/Desktop/SLAC/xrsdkit/xrsdkit/visualization/gui.py", line 643, in _next_data_file
    current_file_idx = file_list.index(current_file)
ValueError: 'xrsdkit_modeling/flowreactor_pd_nanoparticles/dataset/RxnA_201902/RxnA_201902_5_dz_bgsub.dat' is not in list

**Comment by lensonp** [comment]
@Katy-katy - That's unfortunate. I cannot reproduce this issue. Can you figure out why it's happening? Are you positive that you're using the most updated versions and correct branches in both repositories?

**Comment by lensonp** [comment]
@Katy-katy - It looks like the file path is somehow getting cut off:
 
>> 'xrsdkit_modeling/flowreactor_pd_nanoparticles/dataset/RxnA_201902/RxnA_201902_5_dz_bgsub.dat' is not in list

This path is missing the '/Users/kate/Desktop/SLAC/' part. Maybe this is a platform-dependent bug?

**Comment by lensonp** [comment]
@Katy-katy - Ok, I might have figured it out. To reproduce the bug, I had to try to load two directories. The first one loads ok, and then the second one correctly identifies that the "current" file is not in the list. Makes sense.

**Comment by lensonp** [comment]
@Katy-katy - Also, the widgets in the gui keep trying to resize whenever I drag the mouse over it. I'm fixing this as well, because it makes the gui slow and awkward to use. Now I remember that this is why I rolled those changes back last time too. Can you figure out how to get the gui to display on your machine without assigning column weights? Maybe we need a maximum width assigned to the plot window?

**Comment by Katy-katy** [comment]
@lensonp The loading of data now works! I am working on gui for mac now.

**Comment by Katy-katy** [comment]
@lensonp Try if - work well on my machine (no side-effect)

**Pull request merged**
