### PR TITLE
training from a list of dirs

### PR DESCRIPTION
**Pull request by Katy-katy**
@lensonp the huge block of code are selected in read since I change the indention: for example, I added line:

for path_to_dir in list_of_paths_to_dir:

and then I add "tab" the the code below.

### CODE REVIEW

**Comment by lensonp** [comment]
@Katy-katy - Great- will review this first thing tomorrow.

**Comment by lensonp** [comment]
@Katy-katy - This looks good to me. I made some minor changes, see the last commit. 

The only problem is that a test is needed, and we need to update the testing dataset for this as well as for other test functions. I will do that now.

**Comment by lensonp** [comment]
@Katy-katy - About your last commit, where you put:
v.to_csv(k + "/dataset_index.csv")

You should always use os.path for this:
v.to_csv(os.path.join(k,"dataset_index.csv"))

I will change it.

**Comment by lensonp** [comment]
@Katy-katy - I think this is done, but can you review it one more time? If you approve, please go ahead and merge it.

Note that I added two rather large testing datasets. Do you think they should be larger/smaller/different? Feel free to change them. I built them from the newly-repaired datasets in the xrsdkit_modeling repository.

**Comment by Katy-katy** [comment]
@lensonp OK - I will review it

**Pull request merged**
