### PR TITLE
Taxonomy

### PR DESCRIPTION
**Pull request by lensonp**
Tons of changes in this: refactored the system description to use classes instead of structured dictionaries, and then propagated the changes through the whole package.

### CODE REVIEW

**Comment by lensonp** [comment]
@Katy-katy I'm done with it for now. If you approve, then approve. If you see mistakes, then, comment and request changes.

**Comment by Katy-katy** [comment]
@lensonp , it looks like there is a bug in unpack_pif(): 
classification_labels[basis_cls_label] = cls_dict.pop(basis_cls_label).value
KeyError: 'pop0_basis_classification'

I think, I can fixed it on Monday and then we can merge it.

**Comment by lensonp** [comment]
I'll take care of this. Most likely, I forgot to upload basis classifiers for some of the records. It will be a quick fix.

**Comment by lensonp** [comment]
@Katy-katy 

Please review these last few commits. Most importantly:

- review the changes to citrination_tools.py: I changed how the PIF records get extracted into the DataFrame

- test_models.py passes now, but with a warning about setting values in a copy of a DataFrame. Do you know what this warning is about? Should we be doing something differently?

**Comment by Katy-katy** [comment]
@lensonp I merged it and I am going to investigate the " warning about setting values in a copy of a DataFrame"

**Pull request merged**
