### PR TITLE
Group assignments

### PR DESCRIPTION
**Pull request by lensonp**
The group assignment algorithm:

0) base class implementation: 
- assign group_id based on experiment_id
- set group_id to zero if no experiment_id
- return False (untrainable) if there is no variance in the target

1) regressor implementation:
- execute base class implementation
- if there is only one group, split it with KMeans
- if any groups have zero variance in the target, redistribute these groups with KMeans

2) classifier implementation:
- execute base class implementation
- if any labels do not have at least 2 representative samples, remove these labels (by assigning the samples group_id to 0)
- if this leaves us with only one label, return False (untrainable)
- identify underrepresented groups (any groups that do not have at least one sample for each label)
- attempt to pair underrepresented groups to make fully represented groups
- if no fully represented pairings exists, pair for maximal representation of labels
- if there are no other underrepresented groups, assign the underrepresented group to a fully represented group such that the standard deviation of label counts is minimized
- if this process leaves us with only one group, split it into two groups by KMeans

### CODE REVIEW

**Comment by lensonp** [comment]
Not sure why this is failing- I just passed it on my machine. I'll fix and push.

**Comment by lensonp** [comment]
@Katy-katy - This is now ready for review.

**Comment by Katy-katy** [comment]
@lensonp OK - will do it in the next couple of hours (I am moving home now)

**Comment by Katy-katy** [comment]
@lensonp Everything looks fine, but I am getting a very low F1 score for the main classifier Label-averaged unweighted F1 score: 0.17. In the dev branch we have  F1 score: 0.43. It is possible that we have a bug related with reporting the score, but I did not find it yet. I will continue the investigation tomorrow morning

**Comment by lensonp** [comment]
@Katy-katy - Ok, sounds good. Are you testing this on the full dataset?

**Comment by Katy-katy** [comment]
@lensonp yes - I am using the full dataset

**Comment by lensonp** [comment]
@Katy-katy -- I *think* this is working now. The K-means results are somewhat stochastic, so the bugs were hard to find, but it has passed the tests 10 times in a row now... I will run the test a few more times before we merge... but you can review it now for bugs. 

I've been looking at this problem for a little bit too long, and may have lost some perspective on it. See if you can go through the logic in Classifier.assign_groups() and Regressor.assign_groups()... and look for bad logic, or maybe better ways to achieve the desired results.

One thing that would __definitely__ make this better: for the group splitting, we are currently using K-means, which tends to give unbalanced cluster sizes. If we can replace the KMeans with a balanced clustering algorithm that is still reasonably fast, that would greatly improve the balancing of the train/test splits.

**Comment by lensonp** [comment]
@Katy-katy - Darn, it looks like the build failed on the 11th try. I'll fix and push.

**Comment by lensonp** [comment]
@Katy-katy - Ok, I think I tracked down the bug. It is ready for review.

**Pull request merged**
