### PR TITLE
Train from local

### PR DESCRIPTION
**Pull request by Katy-katy**
It includes 48 samples (yml and dat for each sample)

### CODE REVIEW

**Comment by Katy-katy** [comment]
@lensonp I commented out visualization test since it did not work with Python2.7. (there was a problem with DISPLAY variable). I tried to fix it using 
if 'DISPLAY' in os.environ:
    matplotlib.use("TkAgg")
But it also did not work. If you have any idea how to fix it -please, do it!

 It looks like that before this function did not run since we did not get data from Citrination for on-line testing and the df was None:
def test_visualization():
    if df is not None:
        visualize_dataframe(df)

**Comment by lensonp** [comment]
@Katy-katy Why is the visualization test failing for python 2.7? Can you post the error that you are having? It would be better to fix the test than to remove it.

**Comment by lensonp** [comment]
@Katy-katy - Oops, you answered my question as I was asking it. Please ignore!

**Comment by lensonp** [comment]
I can revisit this and fix the bug this afternoon.

**Comment by lensonp** [comment]
@Katy-katy : why was 

self.scaler_y = None

removed from Regressor.__init__?

**Comment by Katy-katy** [comment]
@lensonp There was a bug. Look: 
When we initialize a Regressor: 
def __init__(self,label,yml_file):
        super(Regressor,self).__init__(label, yml_file)
        ....
In the __init__ for xrsdkit model we call :
content = yaml.load(open(yml_file,'rb'))
"load" is a function from the Regressor class where we create self.y_scaler:
`def load_model_data(self,model_data):
        super(Regressor,self).load_model_data(model_data)
        self.scaler_y = preprocessing.StandardScaler()
        if self.trained:
            setattr(self.scaler_y, 'mean_', np.array(model_data['scaler_y']['mean_']))
            setattr(self.scaler_y, 'scale_', np.array(model_data['scaler_y']['scale_']))`

then the control flow goes back to __init__ of Regressor and we had self.scaler_y = None, but it this case self.scaler became "None". 

I found this bug when I tried to "predict" without training (the error was something like: "None type cannot be used for transforming" . It worked if we train and then predict since at training time we fit the scaler_y.

**Comment by lensonp** [comment]
Got it. I like to ensure instance attributes always have a reference defined after the constructor, so I am moving this to before the super().__init__.

**Comment by Katy-katy** [comment]
@lensonp Great! I've just realized that we do not create self.scaler_y if we do not have yml file for this model

**Pull request closed without merging**
