### PR TITLE
Basis classifiers

### PR DESCRIPTION
**Pull request by lensonp**
This seems to be nearly ready to merge. 

If we need to make more changes to the basis classifiers, let's do it as part of this merge.

### CODE REVIEW

**Comment by Katy-katy** [comment]
@lensonp let me review it tomorrow morning

**Comment by lensonp** [comment]
No rush!

**Comment by Katy-katy** [comment]
@lensonp , there is output of "predict":
screen shot 2018-09-25 at 4 51 49 pm

**Comment by Katy-katy** [comment]
@lensonp , there is output that include a crystalline population: 

screen shot 2018-09-25 at 5 01 53 pm

**Comment by lensonp** [comment]
@Katy-katy This is better, but you are still missing the population parameters.

**Comment by Katy-katy** [comment]
@lensonp O...I see! Let me fix it

**Comment by lensonp** [comment]
@Katy-katy - start with what I just pushed.

**Comment by Katy-katy** [comment]
@lensonp yes, I already started with it (for some reasons I've just got your last comment)

**Comment by Katy-katy** [comment]
@lensonp I think, when we save the model in a yml file, we also need to save value for model.trained (True or False). Or, we can save only the models with model.trained==True. It looks like that right now, when we load the models from yml files, we always have "False" for model.trained.

**Pull request merged**
