### PR TITLE
Sys class metrics3

### PR DESCRIPTION
**Pull request by lensonp**
Does this give the desired results? It is an attempt to create the classifier "predicted" dataframe without passing it around as an argument through the model training process. 

I am sure I left some bugs behind.

Please, do not merge this yet. I also want to review the "inconsistent predictions" part of xrsdkit.models.train, starting at line 212. I have looked at it, but I still cannot understand it.

### CODE REVIEW

**Comment by lensonp** [comment]
@Katy-katy - I see. I removed the 'data_file' column because it appeared to be unused. It sounds like you were making use of it externally, in the context of the jupyter notebook. 

In general, I think it is best for a function to "do one thing, and only one thing". This is at the root of my issues with #211. Functions were being used to do two or three things, by passing objects around as inputs/outputs. It becomes hard to read the code, and in our current state, we have to read our code fairly often.

Is there a way for you to attach the data_file to your results externally?

**Comment by lensonp** [comment]
@Katy-katy - How about this version?

I have moved the cross-validation of the main classifiers to its own separate function. This is not necessarily a good thing, because I had to duplicate some code, but I think it's better in this case. There are only a few duplicated lines, and this saves us from having to go back through the "predicted" dataframe during training-- the training function is already ridiculously complicated as-is.

As a consequence, I also changed how the group_by_pc1() function works. It used to add a group_id column to the input DataFrame. It now returns the group_id assignments as a Series, where the index of the Series equals the index of the DataFrame. Then, the developer decides whether or not the group_id should be added to the DataFrame.

**Comment by Katy-katy** [comment]
@lensonp our code looks much nicer, but we have the same problem. After line 143 in train.py, it is possible to predict diffuse_diffuse for a sample with PREDICTED diffuse = False, since in line 124:

    struct_flag_idx = np.array(pred[struct_nm+'_binary']==flag)

we create sruct_flag_idx based on "true" labels, not on predicted labels.

So, I think, after line 143 we need to check if our predicted sys class is consistent with predicted binary labels. If it is not consistent:
* use combinations of PREDICTED binary labels to find the right model to predict the sys_class. I think, in this case we do not need to train the model - we can directly use the model from our dict of classification models (the predicted system class will be wrong any way). 

I will fix it and make a new pull request in this branch

**Comment by lensonp** [comment]
@Katy-katy - Good catch! Fixed.

I will now look at the 'unidentified' versus null problem.

**Comment by Katy-katy** [comment]
@lensonp I do not remember what we decided about 'data_file' (an additional column in our dataframe that you removed). I used this column for data visualization. To find that sample by the sample_id we need to open each yml file and look inside.

**Comment by lensonp** [comment]
@Katy-katy - There was a function for this in the gui module- I just moved it to ymltools. Try ymltools.match_data_to_yml(yml_files).

**Comment by lensonp** [comment]
@Katy-katy - Meanwhile, I think the main classifier cross-validation is done now. 

- I plugged in 'unidentified' instead of None for the default output.

- I realized that we should not cross-validate the system_classifier on the "predicted" dataset, because the training set will include samples that were flagged incorrectly, so the groupings will be messed up.

**Comment by Katy-katy** [comment]
@lensonp It looks like the creating of df with predicted sys_classes works in the right way now :) 

One more time about  'data_file'. The function match_data_to_yml(data_files,yml_files) takes as input yml_file. But our "predicted" df has only column with experiment_id and sample_id. Assume I have this df and want to plot q_I for the sample R0_201811_1541372847 from experiment R0_201811. I can read all yml files in the directory R0_201811 and find the sample with id == R0_201811_1541372847. But  will take much more time. Before I did: 

    f = open('../xrsdkit_modeling/flowreactor_pd_nanoparticles/dataset/' + exp + '/' + file_name,'r')
    q_I = np.loadtxt(f,dtype=float) 

If you think we should not have the column wiht "data_file" name, it is OK - I will update the code in my notebook with plots.

**Comment by lensonp** [comment]
@Katy-katy - Okay, I changed devtools.dataset_to_csv() so that it now produces a dataset index. I think this is ready for your review.

**Pull request merged**
